### ISSUE TITLE
error building?

### ISSUE THREAD

**Issue by kdm9** [thomasjm/bash-prompt-repro#1]
Forgive my ignorance of nix, but I'm getting an error trying to build this in a fresh docker for debugging. Specifically:

(ran as root in a fresh Ubuntu 24.04 docker container)
```bash
$  sh <(curl -L https://nixos.org/nix/install) --daemon
$ nix --extra-experimental-features nix-command --extra-experimental-features flakes build .
error: flake 'git+file:///bash-prompt-repro' does not provide attribute 'packages.x86_64-linux.default' or 'defaultPackage.x86_64-linux'
```

Sorry for my ignorance of Nix, this could easily be me doing something wrong.

I think I might have found the core of the issue, but need to fiddle with the code within Nix's install to confirm.

best,
K

**Comment by thomasjm** [comment]
The README in this repo provides the steps to build.

(You'll probably want to include the `--extra-experimental-features` args you have here.)

**Comment by kdm9** [comment]
sorry I left out that is exactly what I'm following. I forgot to put the git commands in there, but ran `nix --extra-experimental-features nix-command --extra-experimental-features flakes build .` from within a clone of this repository. Is that not what is in the README?

**Comment by kdm9** [comment]
Or are the comments (e.g. the kernelspec bit of `nix build .#kernelspec -o jupyter_path/kernels/bash/kernel.json`) important?

**Comment by thomasjm** [comment]
BTW I think it's a little problematic to install a Nix daemon into a basic Docker container because it wants systemd; you might have more luck with this (recommended [here](https://nixos.org/manual/nix/stable/installation/installing-docker)):

```shell
docker run -ti ghcr.io/nixos/nix
```

And then:

```shell
export NIX_CONFIG='extra-experimental-features = nix-command flakes'

git clone https://github.com/thomasjm/bash-prompt-repro.git
cd bash-prompt-repo

# Build the kernelspec
nix build .#kernelspec -o jupyter_path/kernels/bash/kernel.json
export JUPYTER_PATH=$(pwd)/jupyter_path

# Run papermill
cd home
nix run .#papermill -- --kernel bash notebook.ipynb out.ipynb
```

**Comment by thomasjm** [comment]
> Or are the comments (e.g. the kernelspec bit of nix build .#kernelspec -o jupyter_path/kernels/bash/kernel.json) important?

Those aren't comments, that's GitHub syntax highlighting interpreting the pound sign weirdly :P

**Comment by kdm9** [comment]
Ahhh, then that's my error! I will retry w/ that docker container and also with the "comment" included -- thanks for hand-holding, as I said this is my first time using nix

best,
K

**Comment by kdm9** [comment]
and as an aside: if you wrap the "word" of the comment in single quotes, github renders it more sensibly

```bash
nix build '.#kernelspec' -o jupyter_path/kernels/bash/kernel.json
```

**Comment by kdm9** [comment]
Great, it's now working, by which I mean I reproduce the crash from https://github.com/takluyver/bash_kernel/issues/142
